Extract all command
wahlflo/eml_analyzer pull request #2
Opened 2021-01-24 21:46 UTC by debragail

added --extract-all command

2021-01-25 21:13 UTC, wahlflo requested changes
Hi, 
thank you for your contribution.
Please delete your uploaded PDFs and the email. 
I requested also some changes for the python code itself.
And the setup.py should also stay the same when merging it - exept the version ;) .

2021-01-25 21:13 UTC, wahlflo commented on eml_analyzer/cli_script.py
> +          path = os.path.join(path, attachment.get_filename())
check case where **path** is a path to file. This case is currently missing

2021-01-25 21:13 UTC, wahlflo commented on eml_analyzer/cli_script.py
> +      print(child.get_filename())
Maybe combine this print out with the print out in line 201: **info('Attachment extracted to {}'.format(path))**

Recommendation:
`info('Attachment "{}" extracted to {}'.format(attachment.get_filename(), path))`

2021-01-25 21:13 UTC, wahlflo commented on setup.py
> +    author="Debra White",
```suggestion
    author="Florian Wahl",
```

2021-01-25 21:13 UTC, wahlflo commented on setup.py
> +    author_email="git@27c1ub.com",
```suggestion
    author_email="florian.wahl.developer@gmail.com",
```

2021-01-25 21:13 UTC, wahlflo commented on setup.py
> +    url="https://github.com/debragail/eml_analyzer",
```suggestion
    url="url="https://github.com/wahlflo/eml_analyzer",
```

2021-04-10 17:12 UTC, wahlflo commented
added the --extract-all command in the commit 82977e719005bd50bd5f8773861e3e9ef162fc53

2021-04-10 17:12 UTC, closed without merging

2021-07-04 09:03 UTC, debragail commented
thanks